### ISSUE TITLE
现在还在维护吗？

### ISSUE THREAD

**Issue by BlurryLight** [LiangYuxuan/NEIE-Assistant#1]
现在使用软件的话会提示IP错误，但是服务器的IP并没有改，可能是服务端在agent段加了验证？

**Comment by LiangYuxuan** [comment]
经过我们抓包分析，所有的请求都没有关于agent的header。

请检查填入的IP和网络，或者尝试使用原版软件登入，以进一步确认问题。

此外，请注意这个repo并非现在已经释出的VB版，VB版的repo在[这里](https://github.com/ranulldd/NEIE-Assistant)。我们可能难以维护他的代码，如果需要进一步帮助，请移步VB版的repo提交issue。

**Comment by zhonghaoyu555** [comment]
:<  开了两个标签页 不小心把issue提交到你这了:P  

vb版会提示IP错误，但是可以从浏览器正常访问API页面，原版软件可以正常登入。
不知道在哪里加了验证了

**Comment by LiangYuxuan** [comment]
你可以尝试参考[这个文档](https://github.com/LiangYuxuan/NEIE-Assistant/wiki/NEIE-HTTP-Communication)里的Step 1，使用RESTful调试工具发送请求，检查返回的内容。

原版的VB程序会在返回为空和不含有“LoginListeningResponse”时弹出IP错误。

**Comment by zhonghaoyu555** [comment]
[image: 内嵌图片 1]
有趣的现象，在访问WSDL的时候会提示404错误。

2016-11-16 1:01 GMT+08:00 LiangYuxuan <notifications@github.com>:

**Comment by zhonghaoyu555** [comment]
[image: 内嵌图片 2]
如果把接口中的ServiceV3的V3去掉，用service的话是可以正常访问的，访问到的接口是serviceV1.
[image: 内嵌图片 4]
但是这个接口的话只有这么几个功能。
我没有太过于深入研究这个系统，难道是是管理员在没有升级客户端的情况下改变了API的接口？不太可能吧
还请解惑

在 2016年11月16日 上午1:17，KING lich <zhonghaoyu555@gmail.com>写道：

**Comment by zhonghaoyu555** [comment]
问题已解决，管理员采用了某种手段使?WSDL返回空白，但是其他接口仍然可用
我把那段判断LoginListeningResponse的注释后成功运行

在 2016年11月16日 上午1:32，KING lich <zhonghaoyu555@gmail.com>写道：

**Comment by LiangYuxuan** [comment]
非常感谢你的分享。
