### ISSUE TITLE
Sth. about the protocol

### ISSUE THREAD

**Issue by Phosphorus15** [LiangYuxuan/NEIE-Assistant#10]
I accidentally found this repo when I'm trying to get rid of NEIE 👍  while I had problem decrypting the data embedded in the SOAP request.

If it's possible, I want to consult you something about how the protocol works and how the data are encoded.

for example, this section might means a `bool` value, but I don't know how it is encoded
`69CA112421D2A3A00642664099C2391A`

**Comment by LiangYuxuan** [comment]
Hi, as it wrote in README.md, we created this project based on [ranulldd/NEIE-Assistant](https://github.com/ranulldd/NEIE-Assistant). That project have implemented encode and decode method in VB, and we convent it into C++ (you can find it in library/C++). We guess that project found the method by disassembling NEIE.

For more information about the usage of encode and decode method or the protocol of NEIE, please check wiki of this project.

**Comment by Phosphorus15** [comment]
Wow, thx for your rapid reply. I'm surprised that NEIE also has a wiki entry. Great job you did, dude 🙂

Meanwhile, you might have noticed that NEIE has been separated into two different sections, i.e. RWT and VLS. The SOAP server distinguish them from the SOAP document below

```xml
<GetClientUpdateDownloadURL
    xmlns="http://www.open.com.cn">
    <licenseTypeCode
        xmlns:SOAPSDK4="http://www.open.com.cn">
        RWT
        </licenseTypeCode>
     ...
```

while actually, all the github-implementations are only capable for the VLS section. What made it so? Is it just because there were no RWT section before?

**Comment by Phosphorus15** [comment]
Well, hey! I have to make a correction. It is more likely that the server distinguish them from the
```xml
<SOAPSDK4:ClientCredential>
    83BCC79913F2...  E37438347941F22F6A873D18CE...
    </SOAPSDK4:ClientCredential>
```
Client Credential, rather than from the license type code. according to my analysis on the packets.

**Comment by LiangYuxuan** [comment]
Oh, while our developing, we found `ClientCredential` in header fixed for no reason. Now we understand how this works.

Maybe all our school chooses VLS coincidentally :P.

**Comment by Phosphorus15** [comment]
Yeah, I see. It's interestingly fixed 【滑稽】. And unfortunately the RWT section is **far more** nasty than the VLS section. Would you mind if I create a branch with RWT support?

**Comment by Phosphorus15** [comment]
BTW, how did you guys get the specific info of quiz database (`.json` files in the `database`) directory. By using some kinds of mogic 🐸? Or because there's a SOAP method to fetch those info?

**Comment by LiangYuxuan** [comment]
We are happy if you can support RWT~

We got the database by dumping SQL file in NEIE.

**Comment by Phosphorus15** [comment]
Which means I have to access the SQL server of our school or even hack into it 😰 (well I'm not fully capable of this)? Or just that there's a SQL file contained in the software directory (which I haven't found, at current).

**Comment by Phosphorus15** [comment]
Will it bother if you contact me by QQ? my number is 704639565

**Comment by LiangYuxuan** [comment]
You can find that SQL file in the software directory, @johnbanq can answer this.

Sorry that I'm not using QQ currently.

**Comment by Phosphorus15** [comment]
It's ok, Thank you for your help. I'll go take classes now XP

**Comment by Phosphorus15** [comment]
How may contact @johnbanq now? Such as email etc. There's a great difference between the local structure of two sections, And I need his help.
