### ISSUE TITLE
数据库及优化储存问题

### ISSUE THREAD

**Issue by LiangYuxuan** [LiangYuxuan/NEIE-Assistant#4]
原版的数据库是以sortID、Num、ID三个字段组成。ID的第一个数字表示Level，sortID表示某一Level下的顺序。

所以在寻找某一Section的ProblemNum和下一Section的ID的时候，需要先整表寻找对应的ID，得到其sortID和ProblemNum，然后再寻找有sortID + 1行中ID的第一个数字为当前Level的ID。

考虑到这种储存方式十分不科学，在这里考虑将储存结构改变。我的想法是将4个Level分开储存，按需加载，此外由于sortID总自增1，所以考虑使用array储存。以Level3为例子：
    [{"num": 0, id: "3111"}, {"num": 0, id: "3112"}, ... ]
那么原来Level3、sortID = n的行就能直接以arr[n - 1]来访问。

来谈谈你们的意见。

**Comment by johnbanq** [comment]
似乎没啥问题，如果对象能包含自身的sortID最好并且打包成对象，这样访问下一单元或者problemnum的时候可以不需要检索

**Comment by LiangYuxuan** [comment]
e.g.
        [{"sortID": 1, "num": 0, id: "3111"}, {"sortID": 2, "num": 0, id: "3112"}, ... ]
