### ISSUE TITLE
想问一下你们接下来的计划

### ISSUE THREAD

**Issue by BlurryLight** [LiangYuxuan/NEIE-Assistant#8]
在readme里面注意到`The next plan is to make it easier to use.`，想问一下你们的打算

项目两个月没更新了，是没有继续维护了吗？
另外，
1.有考虑支持python3吗，现在python3毕竟是趋势，Python3对python2的向下兼容也还行，用的库里面requests库是python2/python3都支持的。
2.有考虑GUI吗

**Comment by LiangYuxuan** [comment]
非常感谢你的关注和PR。我们对Python都不算熟悉，代码写得实在不行，非常感谢你能够引入argprase。

近来几个月我们都因为其他事务导致没办法更新这个项目，但是我们认为这个项目还可以继续完善，包括更友善的用户提示和更优秀的内部封装等。最近的工作集中在测试上，我们在小范围内分发此程序并以此测试来确认内部模块的可靠性，经过测试暂时没有发现问题。

关于你问的两个问题：
1. 我们希望可以支持Python 3，但我们的成员都是在Python 2的环境下编码，所以想继续支持Python 2的支持。当时选择Requests库也是基于此考虑。
2. 我们没有关于GUI的计划。但是我们会考虑用别的方式使程序更易用。
