### ISSUE TITLE
请问有研究读写译的助手吗？

### ISSUE THREAD

**Issue by whllhw** [LiangYuxuan/NEIE-Assistant#9]
在初次使用时没有配置config.json文件的时候会出错，
AttributeError: 'Namespace' object has no attribute 'file'。注释掉该行即可。
另外请问有读写译版本的吗？？谢谢

**Comment by LiangYuxuan** [comment]
请问可以提供一下出现问题的行号吗？

我们手上没有读写译与其API，也不知道是否一致。

**Comment by whllhw** [comment]
Traceback (most recent call last):
  File "main.py", line 280, in <module>
    var['no-file']=args.file
AttributeError: 'Namespace' object has no attribute 'file'
无论加不加参数 nf ，文件存不存在，都会报错。
注释掉280行的 var['no-file']=args.file问题就解决，不知道会不会有副作用。

**Comment by LiangYuxuan** [comment]
非常感谢您的回报。现在已经修复了这个问题了。另外，注释掉并不会产生副作用，现在您可以继续使用。
